### ISSUE TITLE
Exec format error in etcd image

### ISSUE THREAD

**Issue by squishykid** [ZCube/bitnami-compat#20]
/opt/bitnami/scripts/etcd/run.sh: line 38: /opt/bitnami/etcd/bin/etcd: cannot execute binary file: Exec format error

docker pull ghcr.io/zcube/bitnami-compat/etcd:3.4.19-debian-11-r15@sha256:cd24be04de0b05d387ce2daf8292ca7005e40397baad733e30e2542eaeeb50d8

image contains x86 executable instead of arm executable:

```
$ file ~/etcd 
/home/rob/etcd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=FSBJvFHmr1ACg8cTm_55/XpAKBUDXx_P7l65LhXfZ/AjC-86e9h5c96McaiK7A/dmLNcGeVsI7V9bw23l9q, stripped
```

**Comment by ZCube** [comment]
@squishykid 
fixed

```
zcube@node0:~/bitnami-compat$ sudo docker pull ghcr.io/zcube/bitnami-compat/etcd:3.5.4-debian-11-r16
3.5.4-debian-11-r16: Pulling from zcube/bitnami-compat/etcd
8657243f3ec5: Already exists
5c0fc05d9e0d: Already exists
dca8e2fa5774: Already exists
a3a21d37a2f6: Already exists
578038bfe5b3: Already exists
31061cceb9e6: Already exists
e10b32645861: Already exists
274e1f09ddcf: Pull complete
4f4fb700ef54: Pull complete
63bcdcb212ad: Pull complete
4aa8f22a99a3: Pull complete
5683b9bf0ab9: Pull complete
Digest: sha256:b975939a2739c8454744d1233c9432f4bd1fc43a42349d126a0b94b364eb3299
Status: Downloaded newer image for ghcr.io/zcube/bitnami-compat/etcd:3.5.4-debian-11-r16
ghcr.io/zcube/bitnami-compat/etcd:3.5.4-debian-11-r16
zcube@node0:~/bitnami-compat$ sudo docker run --pull --rm -ti ghcr.io/zcube/bitnami-compat/etcd:3.5.4-debian-11-r16 etcd --version
etcd 10:51:08.75
etcd 10:51:08.75 Welcome to the Bitnami etcd container
etcd 10:51:08.76 Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 10:51:08.76 Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 10:51:08.77

etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.16.15
Go OS/Arch: linux/arm64
```

**Comment by shyandsy** [comment]
it doesnt work for me for Mac M1 pro chip

```
$ docker pull ghcr.io/zcube/bitnami-compat/etcd:3.5.4-debian-11-r16
3.5.4-debian-11-r16: Pulling from zcube/bitnami-compat/etcd
manifest unknown
```

**Comment by ddelange** [comment]
hi @shyandsy please check which tags are [currently](https://github.com/ZCube/bitnami-compat#supported-images-and-tags) built by this repo, see also [this thread](https://github.com/ZCube/bitnami-compat/issues/55)

**Comment by shyandsy** [comment]
it still not work

my dockerfile shows below
```
FROM ghcr.io/zcube/bitnami-compat/etcd:3.5
```

and my docker compose file
```
  etcd:                                  # container name
    build:
      context: ./etcd                    # use the dockerfile shows above
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:                               # 设置端口映射
      - "${ETCD_PORT}:2379"
    networks:
      - backend
    restart: always
```

the console output for compose up shows like
```
$ docker-compose up -d etcd         
[+] Running 0/0
 ⠿ Container gonivinck-etcd-1                                                                                                [+] Running 0/2           Starting 0.1s
 ⠿ Container gonivinck-etcd-1                                                                                                [+] Running 0/2           Starting 0.2s
 ⠿ Container gonivinck-etcd-1                                                                                                [+] Running 1/2           Starting 0.3s
 ⠿ Container gonivinck-etcd-1                                                                                                                          Started 0.3s
 ⠸ etcd The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
```

**Comment by shyandsy** [comment]
> 

thanks you very quick reply

**Comment by shyandsy** [comment]
> hi @shyandsy please check which tags are [currently](https://github.com/ZCube/bitnami-compat#supported-images-and-tags) built by this repo, see also [this thread](https://github.com/ZCube/bitnami-compat/issues/55)
> 
> in your case I would specify `ghcr.io/zcube/bitnami-compat/etcd:3.5` also to make sure you get bugfixes and security patches 👍

thanks for your very quick reply

**Comment by ddelange** [comment]
(`linux/arm64` is an alias of `linux/arm64/v8`)

**Comment by shyandsy** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/5271457/212671240-7ec46169-6660-4c45-abf6-607c220627fb.png">
its very slow to build the image, but it looks like works

**Comment by ddelange** [comment]
happy to hear :) here's a link to [`dockersize`](https://stackoverflow.com/a/73108928/5511061) for future reference 👍
